name: space_immo
description: "S'PACE - Application immobilière de prestige avec visites 360° et simulation en réalité augmentée"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  lucide_icons_flutter: ^3.1.14+2
  panorama_viewer: ^2.0.7
  google_fonts: ^6.1.0
  intl: ^0.19.0
  dchs_motion_sensors: ^2.0.2
  camera: ^0.11.1
  permission_handler: ^11.3.1
  model_viewer_plus: ^1.10.0
  hive_flutter: ^1.1.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
